spring:
  application:
    name: demo-service2
server:
  port: 9091

azure:
  application-insights:
    instrumentation-key: ${INSTRUMENTAION_KEY}
    enabled: true
    web:
      enabled: true
      enable-W3C: true
 