spring:
  application:
    name: demo-service1
server:
  port: 9090

#logging:
#  level:
#    org:
#      springframework: DEBUG

azure:
  application-insights:
    instrumentation-key: ${INSTRUMENTAION_KEY}
    enabled: true
    web:
      enabled: true
      enable-W3C: true
  cosmosdb:
    uri: ${COSMOSDB_URI}
    key: ${COSMOSDB_KEY}
    database: ${DATABASE}

sample:
  app:
    service2: ${SERVICE2_URL}